//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ARSNETEntities : DbContext
    {
        public ARSNETEntities()
            : base("name=ARSNETEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<FirearmCount> FirearmCounts { get; set; }
        public virtual DbSet<InventoryGroup> InventoryGroups { get; set; }
        public virtual DbSet<InventoryGroupProduct> InventoryGroupProducts { get; set; }
        public virtual DbSet<InventoryGroupProductByMachine> InventoryGroupProductByMachines { get; set; }
        public virtual DbSet<Manufacturer> Manufacturers { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductStockAdjustment> ProductStockAdjustments { get; set; }
        public virtual DbSet<FirearmInventory> FirearmInventories { get; set; }
        public virtual DbSet<OutboundFirearm> OutboundFirearms { get; set; }
        public virtual DbSet<CompanyStore> CompanyStores { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<SerialUPC> SerialUPCs { get; set; }
    }
}
