//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyStore
    {
        public int CompanyStoreID { get; set; }
        public int CompanyID { get; set; }
        public string StoreKey { get; set; }
        public string StoreName { get; set; }
        public string StoreNumber { get; set; }
        public int WorkWeekStartDay { get; set; }
        public string BasePath { get; set; }
        public string SMTPOut { get; set; }
        public string OutgoingEmailUsername { get; set; }
        public string OutgoingEmailPassword { get; set; }
        public string ReturnEmailAddr { get; set; }
        public int POSTimeoutSeconds { get; set; }
        public int LayawayDownPmtPct { get; set; }
        public int SpecialOrderDownPmtPct { get; set; }
        public string QbPtFileName { get; set; }
        public string QbPtFilePath { get; set; }
        public Nullable<System.DateTime> InstallationDate { get; set; }
        public Nullable<System.DateTime> ConversionDate { get; set; }
        public Nullable<System.DateTime> AccountingPostingPeriodCutoffDate { get; set; }
        public string PBlock { get; set; }
        public Nullable<decimal> GiftCardLimit { get; set; }
        public Nullable<int> LongGunWaitingDays { get; set; }
        public Nullable<int> HandGunWaitingDays { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public decimal DiscountLimitPct { get; set; }
        public int MembershipExpirationNotice { get; set; }
        public int LayawayPaymentDueNotice { get; set; }
        public int BirthdayCardAdvance { get; set; }
        public int CreditCardExpirationNotice { get; set; }
        public int HouseAccountDueNotice { get; set; }
        public string EmailAddrBoundBookPrintNotice { get; set; }
        public bool ClassRegistrationCloud { get; set; }
        public bool GiftCardPurchaseCloud { get; set; }
        public bool ListNewGunsOnline { get; set; }
        public bool ListUsedGunsOnline { get; set; }
        public bool RangeReservationsCloud { get; set; }
        public string EmailAddrFed33104 { get; set; }
        public string EmailAddrCLEO33104 { get; set; }
        public string FaxNumberFed331012 { get; set; }
        public long LastSynchTick { get; set; }
        public string POSBackground { get; set; }
        public string EmailReceiving { get; set; }
        public string EmailPurchasing { get; set; }
        public string EmailFirearms { get; set; }
        public string EmailStoreManager { get; set; }
        public string ServerName { get; set; }
        public int LayawayRestockingPct { get; set; }
        public int SpecialOrderRestockingPct { get; set; }
        public string PasswordPolicy { get; set; }
        public int SMTPPort { get; set; }
        public bool AutoPrintFirearmReceipt { get; set; }
        public string DataCenterVersion { get; set; }
        public string RegisterVersion { get; set; }
        public bool GenderRequired { get; set; }
        public bool ShowOverShortAmounts { get; set; }
        public bool PrintCustomerPhoneNumberOnReceipt { get; set; }
        public bool LayawayTaxDueAtInception { get; set; }
        public bool EnableSSL { get; set; }
        public Nullable<bool> RequireCustomer { get; set; }
        public Nullable<bool> AutomaticPay { get; set; }
        public string DbVersion { get; set; }
        public byte AccountingType { get; set; }
        public bool PrintLabelsInReceivingDefault { get; set; }
        public bool PrintLabelsInInvoicingDefault { get; set; }
        public Nullable<bool> IsVendorProductDetailsDisabled { get; set; }
        public bool IsInstalledStore { get; set; }
        public bool IsMultistoreEnabled { get; set; }
        public bool IsApiEnabled { get; set; }
        public byte SalesOrderLockMinutes { get; set; }
        public bool IsQuickLoginEnabled { get; set; }
        public string EmailCloudNotification { get; set; }
        public Nullable<int> VendorID { get; set; }
        public bool ReceiveFirearmSerialNumber { get; set; }
        public bool ReceiveNonFirearmSerialNumber { get; set; }
        public bool IsCreditHoldEnabled { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
