//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeXRole
    {
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public int EmployeeID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Role Role { get; set; }
    }
}
