//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.InventoryGroups = new HashSet<InventoryGroup>();
            this.InventoryGroups1 = new HashSet<InventoryGroup>();
            this.ProductStockAdjustments = new HashSet<ProductStockAdjustment>();
            this.EmployeeXRoles = new HashSet<EmployeeXRole>();
        }
    
        public int EmployeeID { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Title { get; set; }
        public System.DateTime DateOfHire { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public int SecurityLevel { get; set; }
        public string EmployeeNumber { get; set; }
        public string SSN { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public string PasswordEncrypted { get; set; }
        public string PasswordHashed { get; set; }
        public Nullable<System.DateTime> PasswordDate { get; set; }
        public bool IsLockedOut { get; set; }
        public Nullable<System.DateTime> LockedOutDateTime { get; set; }
        public string QuickLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryGroup> InventoryGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryGroup> InventoryGroups1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStockAdjustment> ProductStockAdjustments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeXRole> EmployeeXRoles { get; set; }
    }
}
