//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirearmCount
    {
        public long FirearmCountID { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public int InventoryNumber { get; set; }
        public System.DateTime CountDateTime { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
    
        public virtual FirearmInventory FirearmInventory { get; set; }
    }
}
