//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirearmInventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FirearmInventory()
        {
            this.FirearmCounts = new HashSet<FirearmCount>();
            this.OutboundFirearms = new HashSet<OutboundFirearm>();
        }
    
        public int InventoryNumber { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<decimal> BarrelLength { get; set; }
        public string GaugeCaliber { get; set; }
        public string TypeOfAction { get; set; }
        public string Description { get; set; }
        public string Condition { get; set; }
        public string Status { get; set; }
        public string Location { get; set; }
        public Nullable<bool> PublicDisplay { get; set; }
        public Nullable<bool> Antique { get; set; }
        public Nullable<bool> HideRetail { get; set; }
        public string Importer { get; set; }
        public long ProductID { get; set; }
        public string UPC { get; set; }
        public string ManufacturerNbr { get; set; }
        public Nullable<long> InvNbr { get; set; }
        public string NewUsed { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastScanDateTime { get; set; }
        public int FFLID { get; set; }
        public long BoundBookNumber { get; set; }
        public int RevisionNumber { get; set; }
        public bool IsLatestRevision { get; set; }
        public Nullable<int> BoundBookRecordGroupID { get; set; }
        public string AdditionalInformation { get; set; }
        public bool IsForm331012Firearm { get; set; }
        public Nullable<decimal> ReceivedCost { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FirearmCount> FirearmCounts { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutboundFirearm> OutboundFirearms { get; set; }
    }
}
