//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GunsmithFirearmInventory
    {
        public int GunsmithFirearmInventoryID { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public long TransactionNumber { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public string Manufacturer { get; set; }
        public string Model { get; set; }
        public string SerialNumber { get; set; }
        public string GaugeCaliber { get; set; }
        public string TypeOfAction { get; set; }
        public string Status { get; set; }
        public System.DateTime DateIn { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public Nullable<int> CustomerOutID { get; set; }
        public Nullable<int> VendorOutID { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public string Importer { get; set; }
        public Nullable<long> OutboundTransactionNumber { get; set; }
        public Nullable<System.DateTime> LastScanDateTime { get; set; }
        public int FFLID { get; set; }
        public Nullable<long> AcquisitionAddressID { get; set; }
        public Nullable<long> DispositionAddressID { get; set; }
        public Nullable<long> E4473ID { get; set; }
        public string NICSApprovalCode { get; set; }
        public string TransactionSerialNumber { get; set; }
        public long LogNumber { get; set; }
        public long BoundBookNumber { get; set; }
        public int RevisionNumber { get; set; }
        public bool IsLatestRevision { get; set; }
        public Nullable<int> BoundBookRecordGroupID { get; set; }
        public string AdditionalInformation { get; set; }
    }
}
