//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryGroup()
        {
            this.InventoryGroupProducts = new HashSet<InventoryGroupProduct>();
        }
    
        public int InventoryGroupID { get; set; }
        public int CompanyStoreId { get; set; }
        public string GroupName { get; set; }
        public Nullable<System.DateTime> LastCountSubmitDate { get; set; }
        public Nullable<int> LastCountSubmitEmployeeId { get; set; }
        public bool IsStockTakingComplete { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int CreatedEmployeeId { get; set; }
        public string CreatedMachine { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryGroupProduct> InventoryGroupProducts { get; set; }
    }
}
