//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryGroupProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryGroupProduct()
        {
            this.InventoryGroupProductByMachines = new HashSet<InventoryGroupProductByMachine>();
        }
    
        public long InventoryGroupProductID { get; set; }
        public int InventoryGroupID { get; set; }
        public long ProductID { get; set; }
        public Nullable<int> ProductStockAdjustmentID { get; set; }
        public string StockDiscrepancyReason { get; set; }
    
        public virtual InventoryGroup InventoryGroup { get; set; }
        public virtual Product Product { get; set; }
        public virtual ProductStockAdjustment ProductStockAdjustment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryGroupProductByMachine> InventoryGroupProductByMachines { get; set; }
    }
}
