//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutboundFirearm
    {
        public long OutboundFirearmID { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public long TransactionNumber { get; set; }
        public int InventoryNumber { get; set; }
        public decimal Cost { get; set; }
        public decimal Price { get; set; }
        public decimal COGSAmount { get; set; }
        public Nullable<int> DiscountDetailID { get; set; }
        public Nullable<System.DateTime> DispositionDate { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public Nullable<bool> Returned { get; set; }
        public Nullable<bool> Voided { get; set; }
        public Nullable<long> DispositionAddressID { get; set; }
        public Nullable<long> E4473ID { get; set; }
        public string NICSApprovalCode { get; set; }
        public string TransactionSerialNumber { get; set; }
    
        public virtual FirearmInventory FirearmInventory { get; set; }
    }
}
