//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestWCFServiceLibrary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStockAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductStockAdjustment()
        {
            this.InventoryGroupProducts = new HashSet<InventoryGroupProduct>();
        }
    
        public int ProductStockAdjustmentID { get; set; }
        public int CompanyID { get; set; }
        public int StoreID { get; set; }
        public long ProductID { get; set; }
        public System.DateTime DateStockTaken { get; set; }
        public int StockVerifiedByEmployeeID { get; set; }
        public int QOHOnBooks { get; set; }
        public int QOHActual { get; set; }
        public decimal ValueOnHandOnStockTakingDate { get; set; }
        public string StockDiscrepancyReason { get; set; }
        public int UpdateUserID { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateMachineName { get; set; }
        public bool Active { get; set; }
        public Nullable<decimal> CostVariance { get; set; }
        public bool IsCLXSent { get; set; }
        public decimal AverageCost { get; set; }
        public decimal LastCost { get; set; }
    
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryGroupProduct> InventoryGroupProducts { get; set; }
        public virtual Product Product { get; set; }
    }
}
